[auth]
redirect_uri = "http://150.230.98.136:8501/oauth2callback"
cookie_secret = "streamlit_user"

[auth.keycloak]
client_id = "myclient"
client_secret = "F1M3Im4i6yFZ9LG49LauBgC4PbasqRv9a"
server_metadata_url = "http://150.230.98.136:18080/realms/myrealm/.well-known/openid-configuration"