[auth]
redirect_uri = "http://150.230.98.136:8501/oauth2callback"
cookie_secret = "streamlit_user"

[auth.keycloak]
client_id = "myclient"
client_secret = "F1M3Im4i6yFZ9LG49LauBgC4PbasqRv9"
server_metadata_url = "http://150.230.98.136:18080/realms/myrealm/.well-known/openid-configuration"

[keycloak]
server_url = "http://150.230.98.136:18080/"
realm_name = "myrealm"
client_id = "myclient"
client_secret = "F1M3Im4i6yFZ9LG49LauBgC4PbasqRv9"

[llm]
api_key = "ollama"
base_url = "http://141.148.80.136:11434/v1"